config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"

  resources :products do
    resources :reviews, only: [:create, :edit, :destroy, :new, :update]
  end

  resource :user, only:[:new, :create]
  resource :session, only:[:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :user
  has_many :reviews


  validates :name, :description, :price, :url, presence: true
  validates :price, numericality: { greater_than: 0 }


end

app/models/review.rb
class Review < ApplicationRecord


  belongs_to :product
  belongs_to :user


  validates :description, presence: true, length: { minimum: 4 }


end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :products
  has_many :reviews
  PASSWORD_FORMAT = /\A
  	  (?=.{8,})          # Must contain 8 or more characters
  	  (?=.*\d)           # Must contain a digit
  	  (?=.*[a-z])        # Must contain a lower case character
  	  (?=.*[A-Z])        # Must contain an upper case character
  	  (?=.*[[:^alnum:]]) # Must contain a symbol
  	/x

  	validates :password, presence: true, length: {:within => 6..40}, format: { with: PASSWORD_FORMAT }, confirmation: true, on: :create
  	validates :password, allow_nil: true, length: {:within => 6..40}, format: { with: PASSWORD_FORMAT }, confirmation: true, on: :update

  	validates :email, presence: true, uniqueness: true
  	validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  	validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\z/,message: "Only letters and Numbers are allowed" }

  	validates :first_name,presence: true, format: { with: /\A[a-zA-Z]+\z/,message: "Only letters are allowed" }
      validates :last_name,presence: true, format: { with: /\A[a-zA-Z]+\z/,message: "Only letters are allowed" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_url
    end
  end

  def require_login
    	# Check if session has user_id nil
    	if session[:user_id] == nil
    		# Redirect to root path
    		redirect_to root_path
    	end
    end


    helper_method :current_user


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :ensure_logged_in, except: [:show, :index]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def update
    @product = Product.find(params[:id])
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price = params[:product][:price]

    if @product.save
      redirect_to product_url(@product.id)
    else
      redirect_to product_path
    end
  end

  def create
    @product = Product.new
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price = params[:product][:price]
    @product.url = params[:product][:url]
    @product.user_id = current_user.id
    if @product.save
      redirect_to product_url(@product.id)
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
  @review = Review.new
  @review.description = params[:review][:description]
  @review.product_id = params[:product_id]
  @review.user_id=current_user.id
  @review.save
  redirect_to product_url(params[:product_id])
  end

  def edit
    @review = Review.find(params[:id])
    @product = Product.find(params[:product_id])
  end

  def update
    @review = Review.find(params[:id])
    @review.description = params[:review][:description]
    @review.product_id = params[:product_id]
    @review.save
    redirect_to product_path(params[:product_id])
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_url(@product.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to products_url, notice: "Logged in!"
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Make Sure user is logged in
  before_action :require_login, only: %i(profile update changePassword)

  def profile
    @user = current_user
  end

  def new
  	@user = User.new
  end



  def create
  	@user = User.new(user_params)
  	# If user get saved to database
  	if @user.save
  		redirect_to root_path
  	else
  	#If there is error while saving to database
  		render :new
  	end

  end


  def update
    if current_user.update_attributes(user_update_params)
      #set Message
    else
      #set Message
    end

    redirect_to user_profile_path

  end


  def changePassword
     user = User.find_by_username(current_user.username)
      # If the user exists AND the password entered is correct.
      if user && user.authenticate(params[:update_password][:old_password]) && params[:update_password][:password] == params[:update_password][:password_confirmation]
        user.password = params[:update_password][:password]
        if user.save
          #set Message
        else
          #set Message
        end
      else
       # set Message; Password dosn't match with confirm
      end
      redirect_to user_profile_path
  end

  def login
  	@user = User.new
  end


  def destroy

    if current_user.delete
      redirect_to root_path
    else
     #Edit Message
     redirect_to user_profile_path
    end

  end



  private

  def user_params
  	params.require(:user).permit(:first_name,:last_name,:username,:email,:password,:password_confirmation)
  end

  def user_update_params
    params.require(:user).permit(:first_name,:last_name,:username,:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Adding Bootstrap -->
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css', media: 'all' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js' %>
    <!-- End Bootstrap -->
  </head>

  <body>
    <header class="header">
      <h1 class="logo"> <a href="/products"> Project</a></h1>
      <nav class="navbar">
        <a><%= link_to 'Home', root_path %></a>
        <a><%= link_to 'Products', products_path %></a>
        <a><%= link_to 'Add New Product', new_product_path %></a>
      </nav>
    </header>

    <section class="wrapper">

      <%= yield %>

    </section>
    <p class="userinfo">
    <% if current_user %>
    Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
    <% else %>
    <%= link_to "Log in", new_session_path %> or <%= link_to "Sing up", new_user_path %>
    <% end %>
    </p>
    <footer>
      <p>Footer</p>
    </footer>
  </body>
</html>

app/views/products/_product_form.html.erb
<%= form_for product do |f|  %>
<div class="form-group">
    <h4><%= f.label :name %></h4>
    <h4><%= f.text_field :name %></h4>
</div>
<div class="form-group">
    <h4><%= f.label :description %></h4>
    <h4><%= f.text_area :description %></h4>
  </div>
  <div class="form-group">
    <h4><%= f.label :price %></h4>
    <h4><%= f.number_field :price %></h4>
  </div>
  <div class="form-group">
    <h4><%= f.label :url %></h4>
    <h4><%= f.text_field :url %></h4>
  </div>
    <h4>
    <%= f.submit "Submit", class:"btn btn-primary"%>
    </h4>
<% end %>

<% if product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %> prohibited this article from being saved:</h2>


    <ul>
    <% product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/products/_product_individual.html.erb
<div class="container">
  <div class="picture ">
  <%= link_to image_tag(product.url), product_path(product), :class => "image"%>
  </div>

  <div class="text text-center">
    <%= link_to "#{ product.name }", product_path(product) %>
    <h3 class="description">
      Description: <%= product.description %>
      <br>
      Price: <%= product.price %> CAD
    </h3>
  </div>
</div>

app/views/products/_review.html.erb
<%= form_for(@review , url: product_reviews_path(@product.id)) do |f|  %>

  <%= f.text_field :description %>

  <%= f.submit %>

  <% end %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

app/views/products/edit.html.erb
<div class="edit">
  <h1>Edit</h1>

  <div class="form">
    <%= render 'product_form', product: @product %>
  </div>
</div>

app/views/products/index.html.erb
<section class="index">
  <% @products.each do |product| %>


    <div class="single">
      <%= render "product_individual", product: product %>
    </div>

  <% end %>
</section>

app/views/products/new.html.erb
<div class="new">
  <h1>New Product</h1>

  <div class="form">
    <%= render 'product_form', product: @product %>
  </div>
</div>

app/views/products/show.html.erb
<div class="show">
  <%= render "product_individual", product: @product %>

  <span class="links">
    <%= link_to "Edit", edit_product_path %> |

    <%= link_to "Delete", product_url(@product), method: :delete, data: {confirm: "Are you sure you want to delete this product #{ @product.name }?"} %>
  </span>


  <!-- First we will find the review for the product -->
  <!--  Display the review (review description)  we will show the timestamp-->
  <!--  have a form to add review we make sure the product_id is the same as params[:id] -->
</div>

<div class="review">
  <h2 class="label">Reviews:</h2>
  <% @product.reviews.each do |review| %>

  <ul>
    <li>
      <span class="review-description"><%= review.description %></span>

      <span class="time"><%= review.created_at.asctime %></span>

      <br/>

      <span class="links">
        <%= link_to 'Edit', edit_product_review_path(@product.id,review) %> |
        <%= link_to "Delete", product_review_url(@product.id, review), method: :delete, data: {confirm: "Are you sure you want to delete \"#{ review.description }\"?"} %>
      </span>
    </li>
  </ul>

  <% end %>
  <%=  render 'review' ,locals:{ review: @review , product_id: @product.id } %>
</div>

app/views/reviews/_product_individual.html.erb
<h2><%= link_to "Name: #{ product.name }", product_path(product) %></h2>
<p>
  Description: <%= product.description %>
  <br>
  Price: <%= product.price %> Cents
</p>

app/views/reviews/_review.html.erb
<%= form_for(@review , url: product_review_path(@product,@review)) do |f|  %>

  <%= f.text_field :description %>

  <%= f.submit %>

  <% end %>

app/views/reviews/edit.html.erb
<h1>Update Review</h1>


<%=  render 'review' ,locals:{ review: @review , product_id: @product.id } %>

app/views/users/new.html.erb
<h1>User#new</h1>
<%= form_for @user, url: user_path do |f| %>

<!-- Display Error Message if User didn't saved -->
<% if @user.errors.any? %>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
<!-- End Error Message -->

  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br />

  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br />

  <%= f.label :username %>:
  <%= f.text_field :username %><br />

  <%= f.label :email %>:
  <%= f.text_field :email %><br />

  <%= f.label :password %>:
  <%= f.password_field :password %><br />

  <%= f.label :password_confirmation %>:
  <%= f.password_field :password_confirmation %><br />


  <%= f.submit %>
<% end %>